apiVersion: v1
kind: Pod
metadata:
  name: lables
  namespace: expense
  labels:
    image: nginx
    environment: dev
    Auther: Muneer
    module: backend
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx